#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Bug routes non listées
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation