<?php

namespace App\DataFixtures;

use App\Entity\Promo;
use DateTimeImmutable;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture;

class Promofixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $promo = new Promo();
        $promo->setNom('Soirée foot');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('2 pizzas + 2 canette + 2 dessert');
        $promo->setPizzaQuantity(2);
        $promo->setCanetteQuantity(2);
        $promo->setDessertQuantity(1);                         
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addCanette($this->getReference('coca-canette'));
        $promo->addCanette($this->getReference('fanta-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('ice-tea-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->setSlug('soiree-foot');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Familles nombreuses');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('4 pizzas + 1 bouteille + 4 desserts');
        $promo->setPizzaQuantity(3);
        $promo->setBoissonQuantity(1);
        $promo->setDessertQuantity(4);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addBoisson($this->getReference('coca'));
        $promo->addBoisson($this->getReference('fanta'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('ice-tea'));
        $promo->addBoisson($this->getReference('oasis'));
        $promo->addBoisson($this->getReference('perrier'));
        $promo->addBoisson($this->getReference('evian'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('familles-nombreuses');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu Solo');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 canette + 1 dessert');
        $promo->setPizzaQuantity(1);
        $promo->setCanetteQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addCanette($this->getReference('coca-canette'));
        $promo->addCanette($this->getReference('fanta-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('ice-tea-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('menu-solo');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu famille');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('3 pizzas + 1 boissons + 3 desserts');
        $promo->setPizzaQuantity(3);
        $promo->setBoissonQuantity(1);
        $promo->setDessertQuantity(3);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addBoisson($this->getReference('coca'));
        $promo->addBoisson($this->getReference('fanta'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('ice-tea'));
        $promo->addBoisson($this->getReference('oasis'));
        $promo->addBoisson($this->getReference('perrier'));
        $promo->addBoisson($this->getReference('evian'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('menu-famille');
        $manager->persist($promo);

        

        $promo = new Promo();
        $promo->setNom('Menu enfant');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 dessert');
        $promo->setPizzaQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('menu-enfant');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu trio');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('3 pizzas + 3 canette');
        $promo->setPizzaQuantity(3);
        $promo->setCanetteQuantity(3);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addCanette($this->getReference('coca-canette'));
        $promo->addCanette($this->getReference('fanta-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('ice-tea-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->setSlug('menu-duo');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu famille+');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('4 pizzas + 2 bouteille + 4 desserts');
        $promo->setPizzaQuantity(4);
        $promo->setBoissonQuantity(2);
        $promo->setDessertQuantity(4);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addBoisson($this->getReference('coca'));
        $promo->addBoisson($this->getReference('fanta'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('ice-tea'));
        $promo->addBoisson($this->getReference('oasis'));
        $promo->addBoisson($this->getReference('perrier'));
        $promo->addBoisson($this->getReference('evian'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('menu-famille');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu Complet');
        $promo->setIsActive(true);
        $promo->setImageName('defaultPromo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 canette + 1 dessert');
        $promo->setPizzaQuantity(1);
        $promo->setCanetteQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addBoisson($this->getReference('coca'));
        $promo->addBoisson($this->getReference('fanta'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('ice-tea'));
        $promo->addBoisson($this->getReference('oasis'));
        $promo->addBoisson($this->getReference('perrier'));
        $promo->addBoisson($this->getReference('evian'));
        $promo->addDessert($this->getReference('tiramisu'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-aux-fraises'));
        $promo->addDessert($this->getReference('tarte-aux-framboises'));
        $promo->addDessert($this->getReference('tarte-aux-abricots'));
        $promo->addDessert($this->getReference('tarte-aux-poires'));
        $promo->addDessert($this->getReference('tarte-aux-peches'));
        $promo->addDessert($this->getReference('tarte-aux-myrtilles'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->setSlug('menu-complet');
        $manager->persist($promo);

        $manager->flush();
    }
}
