<?php

namespace App\DataFixtures;

use App\Entity\Promo;
use DateTimeImmutable;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture;

class Promofixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {


        $promo = new Promo();
        $promo->setNom('Soirée foot');
        $promo->setIsActive(true);
        $promo->setImageName('soiree-foot.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('2 pizzas + 2 canette + 2 desserts + 2 extras');
        $promo->setPizzaQuantity(2);
        $promo->setCanetteQuantity(2);
        $promo->setDessertQuantity(2);
        $promo->setExtraQuantity(2);                       
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));


        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));

        $promo->addCanette($this->getReference('coca-cola-canette'));
        $promo->addCanette($this->getReference('coca-zero-canette'));
        $promo->addCanette($this->getReference('coca-cherry-canette'));
        $promo->addCanette($this->getReference('evian-canette'));
        $promo->addCanette($this->getReference('lipton-ice-tea-canette'));
        $promo->addCanette($this->getReference('minute-maid-canette'));
        $promo->addCanette($this->getReference('minute-maid-pomme-canette'));
        $promo->addCanette($this->getReference('minute-maid-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-pomme-cassis-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->addCanette($this->getReference('pepsi-max-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('tropico-canette'));
        $promo->addCanette($this->getReference('fanta-citron-canette'));
        $promo->addCanette($this->getReference('fanta-orange-canette'));
        $promo->addCanette($this->getReference('perrier-canette'));

        $promo->addExtra($this->getReference('nuggets'));
        $promo->addExtra($this->getReference('chicken-wings'));
        $promo->addExtra($this->getReference('onion-rings'));
        $promo->addExtra($this->getReference('frites'));
        $promo->addExtra($this->getReference('potatoes'));
        $promo->addExtra($this->getReference('mozza-sticks'));
        $promo->addExtra($this->getReference('cheese-poppers'));
        $promo->addExtra($this->getReference('tenders'));
        $promo->addExtra($this->getReference('yakitori'));
        $promo->addExtra($this->getReference('bouchees-au-camembert'));
        $promo->addExtra($this->getReference('pain-a-l-ail'));

        $promo->setSlug('soiree-foot');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu Big');
        $promo->setIsActive(true);
        $promo->setImageName('menu-big.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('4 pizzas + 1 bouteille + 3 desserts + 3 extras');
        $promo->setPizzaQuantity(3);
        $promo->setBoissonQuantity(1);
        $promo->setDessertQuantity(3);
        $promo->setExtraQuantity(3);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addBoisson($this->getReference('coca-cola'));
        $promo->addBoisson($this->getReference('coca-cola-zero'));
        $promo->addBoisson($this->getReference('coca-cola-cherry'));
        $promo->addBoisson($this->getReference('7up'));
        $promo->addBoisson($this->getReference('7up-mojito'));
        $promo->addBoisson($this->getReference('canada-dry'));
        $promo->addBoisson($this->getReference('fanta-orange'));
        $promo->addBoisson($this->getReference('fanta-citron'));
        $promo->addBoisson($this->getReference('lipton-ice-tea'));
        $promo->addBoisson($this->getReference('oasis-tropical'));
        $promo->addBoisson($this->getReference('oasis-pomme-cassis'));
        $promo->addBoisson($this->getReference('orangina'));
        $promo->addBoisson($this->getReference('schweppes-agrum'));
        $promo->addBoisson($this->getReference('schweppes-lemon'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('tropico'));
        $promo->addBoisson($this->getReference('perrier'));

        $promo->addExtra($this->getReference('nuggets'));
        $promo->addExtra($this->getReference('chicken-wings'));
        $promo->addExtra($this->getReference('onion-rings'));
        $promo->addExtra($this->getReference('frites'));
        $promo->addExtra($this->getReference('potatoes'));
        $promo->addExtra($this->getReference('mozza-sticks'));
        $promo->addExtra($this->getReference('cheese-poppers'));
        $promo->addExtra($this->getReference('tenders'));
        $promo->addExtra($this->getReference('yakitori'));
        $promo->addExtra($this->getReference('bouchees-au-camembert'));
        $promo->addExtra($this->getReference('pain-a-l-ail'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('familles-nombreuses');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu Solo');
        $promo->setIsActive(true);
        $promo->setImageName('menu-solo.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 canette + 1 dessert');
        $promo->setPizzaQuantity(1);
        $promo->setCanetteQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addCanette($this->getReference('coca-cola-canette'));
        $promo->addCanette($this->getReference('coca-zero-canette'));
        $promo->addCanette($this->getReference('coca-cherry-canette'));
        $promo->addCanette($this->getReference('evian-canette'));
        $promo->addCanette($this->getReference('lipton-ice-tea-canette'));
        $promo->addCanette($this->getReference('minute-maid-canette'));
        $promo->addCanette($this->getReference('minute-maid-pomme-canette'));
        $promo->addCanette($this->getReference('minute-maid-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-pomme-cassis-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->addCanette($this->getReference('pepsi-max-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('tropico-canette'));
        $promo->addCanette($this->getReference('fanta-citron-canette'));
        $promo->addCanette($this->getReference('fanta-orange-canette'));
        $promo->addCanette($this->getReference('perrier-canette'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('menu-solo');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu famille');
        $promo->setIsActive(true);
        $promo->setImageName('menu-famille.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('3 pizzas + 1 boissons + 2 desserts');
        $promo->setPizzaQuantity(2);
        $promo->setBoissonQuantity(1);
        $promo->setDessertQuantity(2);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addBoisson($this->getReference('coca-cola'));
        $promo->addBoisson($this->getReference('coca-cola-zero'));
        $promo->addBoisson($this->getReference('coca-cola-cherry'));
        $promo->addBoisson($this->getReference('7up'));
        $promo->addBoisson($this->getReference('7up-mojito'));
        $promo->addBoisson($this->getReference('canada-dry'));
        $promo->addBoisson($this->getReference('fanta-orange'));
        $promo->addBoisson($this->getReference('fanta-citron'));
        $promo->addBoisson($this->getReference('lipton-ice-tea'));
        $promo->addBoisson($this->getReference('oasis-tropical'));
        $promo->addBoisson($this->getReference('oasis-pomme-cassis'));
        $promo->addBoisson($this->getReference('orangina'));
        $promo->addBoisson($this->getReference('schweppes-agrum'));
        $promo->addBoisson($this->getReference('schweppes-lemon'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('tropico'));
        $promo->addBoisson($this->getReference('perrier'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('menu-famille');
        $manager->persist($promo);

        

        $promo = new Promo();
        $promo->setNom('Menu enfant');
        $promo->setIsActive(true);
        $promo->setImageName('menu-enfant.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 dessert');
        $promo->setPizzaQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('menu-enfant');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu trio');
        $promo->setIsActive(true);
        $promo->setImageName('menu-trio.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('3 pizzas + 3 canette');
        $promo->setPizzaQuantity(3);
        $promo->setCanetteQuantity(3);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addCanette($this->getReference('coca-cola-canette'));
        $promo->addCanette($this->getReference('coca-zero-canette'));
        $promo->addCanette($this->getReference('coca-cherry-canette'));
        $promo->addCanette($this->getReference('evian-canette'));
        $promo->addCanette($this->getReference('lipton-ice-tea-canette'));
        $promo->addCanette($this->getReference('minute-maid-canette'));
        $promo->addCanette($this->getReference('minute-maid-pomme-canette'));
        $promo->addCanette($this->getReference('minute-maid-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-tropical-canette'));
        $promo->addCanette($this->getReference('oasis-pomme-cassis-canette'));
        $promo->addCanette($this->getReference('orangina-canette'));
        $promo->addCanette($this->getReference('pepsi-canette'));
        $promo->addCanette($this->getReference('pepsi-max-canette'));
        $promo->addCanette($this->getReference('sprite-canette'));
        $promo->addCanette($this->getReference('tropico-canette'));
        $promo->addCanette($this->getReference('fanta-citron-canette'));
        $promo->addCanette($this->getReference('fanta-orange-canette'));
        $promo->addCanette($this->getReference('perrier-canette'));
        $promo->setSlug('menu-duo');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu famille+');
        $promo->setIsActive(true);
        $promo->setImageName('menu-famille+.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('4 pizzas + 2 bouteille + 4 desserts + 4 extras');
        $promo->setPizzaQuantity(4);
        $promo->setBoissonQuantity(2);
        $promo->setDessertQuantity(4);
        $promo->setExtraQuantity(4);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addBoisson($this->getReference('coca-cola'));
        $promo->addBoisson($this->getReference('coca-cola-zero'));
        $promo->addBoisson($this->getReference('coca-cola-cherry'));
        $promo->addBoisson($this->getReference('7up'));
        $promo->addBoisson($this->getReference('7up-mojito'));
        $promo->addBoisson($this->getReference('canada-dry'));
        $promo->addBoisson($this->getReference('fanta-orange'));
        $promo->addBoisson($this->getReference('fanta-citron'));
        $promo->addBoisson($this->getReference('lipton-ice-tea'));
        $promo->addBoisson($this->getReference('oasis-tropical'));
        $promo->addBoisson($this->getReference('oasis-pomme-cassis'));
        $promo->addBoisson($this->getReference('orangina'));
        $promo->addBoisson($this->getReference('schweppes-agrum'));
        $promo->addBoisson($this->getReference('schweppes-lemon'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('tropico'));
        $promo->addBoisson($this->getReference('perrier'));

        $promo->addExtra($this->getReference('nuggets'));
        $promo->addExtra($this->getReference('chicken-wings'));
        $promo->addExtra($this->getReference('onion-rings'));
        $promo->addExtra($this->getReference('frites'));
        $promo->addExtra($this->getReference('potatoes'));
        $promo->addExtra($this->getReference('mozza-sticks'));
        $promo->addExtra($this->getReference('cheese-poppers'));
        $promo->addExtra($this->getReference('tenders'));
        $promo->addExtra($this->getReference('yakitori'));
        $promo->addExtra($this->getReference('bouchees-au-camembert'));
        $promo->addExtra($this->getReference('pain-a-l-ail'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('menu-famille');
        $manager->persist($promo);

        $promo = new Promo();
        $promo->setNom('Menu Complet');
        $promo->setIsActive(true);
        $promo->setImageName('menu-complet.jpg');
        $promo->setUpdatedAt(new DateTimeImmutable() );
        $promo->setDescription('1 pizza + 1 canette + 1 dessert + 1 extra');
        $promo->setPizzaQuantity(1);
        $promo->setCanetteQuantity(1);
        $promo->setDessertQuantity(1);
        $promo->setExtraQuantity(1);
        $promo->setPrix(20.00);
        $promo->setIsActive(true);
        $promo->addPizza($this->getReference('margherita'));
        $promo->addPizza($this->getReference('reine'));
        $promo->addPizza($this->getReference('4-fromages'));
        $promo->addPizza($this->getReference('calzone'));
        $promo->addPizza($this->getReference('hawai'));
        $promo->addPizza($this->getReference('vegetarienne'));
        $promo->addPizza($this->getReference('sicilienne'));
        $promo->addPizza($this->getReference('norvegienne'));
        $promo->addPizza($this->getReference('chorizo'));
        $promo->addPizza($this->getReference('bolognaise'));
        $promo->addPizza($this->getReference('fermiere'));
        $promo->addPizza($this->getReference('canibale'));
        $promo->addPizza($this->getReference('raclette'));
        $promo->addPizza($this->getReference('tartiflette'));
        $promo->addPizza($this->getReference('chevre-miel'));
        $promo->addPizza($this->getReference('campionne'));
        $promo->addPizza($this->getReference('4-saisons'));

        $promo->addBoisson($this->getReference('coca-cola'));
        $promo->addBoisson($this->getReference('coca-cola-zero'));
        $promo->addBoisson($this->getReference('coca-cola-cherry'));
        $promo->addBoisson($this->getReference('7up'));
        $promo->addBoisson($this->getReference('7up-mojito'));
        $promo->addBoisson($this->getReference('canada-dry'));
        $promo->addBoisson($this->getReference('fanta-orange'));
        $promo->addBoisson($this->getReference('fanta-citron'));
        $promo->addBoisson($this->getReference('lipton-ice-tea'));
        $promo->addBoisson($this->getReference('oasis-tropical'));
        $promo->addBoisson($this->getReference('oasis-pomme-cassis'));
        $promo->addBoisson($this->getReference('orangina'));
        $promo->addBoisson($this->getReference('schweppes-agrum'));
        $promo->addBoisson($this->getReference('schweppes-lemon'));
        $promo->addBoisson($this->getReference('sprite'));
        $promo->addBoisson($this->getReference('tropico'));
        $promo->addBoisson($this->getReference('perrier'));

        $promo->addExtra($this->getReference('nuggets'));
        $promo->addExtra($this->getReference('chicken-wings'));
        $promo->addExtra($this->getReference('onion-rings'));
        $promo->addExtra($this->getReference('frites'));
        $promo->addExtra($this->getReference('potatoes'));
        $promo->addExtra($this->getReference('mozza-sticks'));
        $promo->addExtra($this->getReference('cheese-poppers'));
        $promo->addExtra($this->getReference('tenders'));
        $promo->addExtra($this->getReference('yakitori'));
        $promo->addExtra($this->getReference('bouchees-au-camembert'));
        $promo->addExtra($this->getReference('pain-a-l-ail'));

        $promo->addDessert($this->getReference('tiramisu-fraise'));
        $promo->addDessert($this->getReference('tiramisu-chocolat'));
        $promo->addDessert($this->getReference('tiramisu-caramel'));
        $promo->addDessert($this->getReference('tarte-aux-daims'));
        $promo->addDessert($this->getReference('tarte-aux-pommes'));
        $promo->addDessert($this->getReference('tarte-au-citron'));
        $promo->addDessert($this->getReference('brownie'));
        $promo->addDessert($this->getReference('muffin-nature'));
        $promo->addDessert($this->getReference('muffin-chocolat'));
        $promo->addDessert($this->getReference('pana-cotta'));
        $promo->addDessert($this->getReference('salade-de-fruits'));
        $promo->addDessert($this->getReference('fondant-au-chocolat'));
        $promo->addDessert($this->getReference('mousse-au-chocolat'));
        $promo->addDessert($this->getReference('flan'));
        $promo->setSlug('menu-complet');
        $manager->persist($promo);

        $manager->flush();
    }
}
